PRODUCTS = [
    {
        "sku": "TOP-1001",
        "name": "轻薄针织开衫",
        "category": "上衣",
        "style": ["通勤", "简约"],
        "season": ["春", "秋"],
        "colors": ["米白", "浅灰", "雾蓝"],
        "price": 239,
    },
    {
        "sku": "TOP-1002",
        "name": "宽松连帽卫衣",
        "category": "上衣",
        "style": ["休闲", "街头"],
        "season": ["春", "秋", "冬"],
        "colors": ["黑色", "卡其", "深蓝"],
        "price": 199,
    },
    {
        "sku": "DRESS-2001",
        "name": "法式碎花连衣裙",
        "category": "裙装",
        "style": ["法式", "约会"],
        "season": ["春", "夏"],
        "colors": ["奶油黄", "浅绿"],
        "price": 329,
    },
    {
        "sku": "PANTS-3001",
        "name": "高腰直筒牛仔裤",
        "category": "裤装",
        "style": ["通勤", "复古"],
        "season": ["四季"],
        "colors": ["深蓝", "水洗蓝"],
        "price": 259,
    },
    {
        "sku": "OUTER-4001",
        "name": "短款风衣外套",
        "category": "外套",
        "style": ["通勤", "轻熟"],
        "season": ["春", "秋"],
        "colors": ["卡其", "军绿"],
        "price": 499,
    },
    {
        "sku": "KNIT-5001",
        "name": "羊毛高领毛衣",
        "category": "上衣",
        "style": ["极简", "保暖"],
        "season": ["秋", "冬"],
        "colors": ["燕麦", "黑色", "棕色"],
        "price": 369,
    },
]
